# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c0ee374768a77e0226eaa0262e926145f1f4d3f84f9d0c20f14a3df44b0a68c64dea43f708e17df2b9f6de615ed0b9088589389975a102e6ce910ae1a7c2da

test:
  secret_key_base: 27ec8458a75e6a7641f8d25c6857dae92fadb2f60a3d51b18088d8faffa42e45be3cf3011d819971a1088859f4cbe8fec54fed35302bbc70b76360839c06e71e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
